### ISSUE TITLE
lm-sasl.c:532:32: error: comparison between pointer and zero character constant

### ISSUE THREAD

**Issue by hashashini** [mcabber/loudmouth#30]
loudmouth-1.5.3 fails to compile with gcc-7.1.0

lm-sasl.c: In function 'sasl_md5_prepare_response':
lm-sasl.c:532:32: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     if (nonce == NULL || nonce == '\0') {
                                ^~

build log at https://bugs.gentoo.org/show_bug.cgi?id=618330

**Comment by hashashini** [comment]
https://github.com/mcabber/loudmouth/pull/31 solves the issue
